Import('jsenv')

jsenv['srcs'].extend(File([
    'ajs_main.c',
    'ajs_malloc.c',
    'ajs_obs_stubs.c'
]))

if jsenv['ENV'].get('YUN_BUILD', '0') == '1':
    jsenv['srcs'].extend(Glob('lininoio/*.c'))
else:
    jsenv['srcs'].extend(File([
        'io/io_simulation.c',
        'io/io_info.c',
        'io/io_stubs.c'
    ]))
