Import('jsenv')

jsenv['use_simio'] = False

jsenv['srcs'] = []

jsenv.Prepend(CPPPATH = [ '$TARG' ])

jsenv.SConscript('$TARG/SConscript')

jsenv['srcs'].extend(Glob('*.c'))
if jsenv['use_simio']:
    jsenv['srcs'].extend(Glob('simio/*.c'))

jsenv['srcs'].append(jsenv['duktape_src'])

jsenv.Program('#dist/bin/alljoynjs', jsenv['srcs'])
