Import('jsenv')

jsenv['srcs'] = []

jsenv.Prepend(CPPPATH = [ '$TARG' ])

jsenv.SConscript('$TARG/SConscript')

jsenv['srcs'].extend(Glob('*.c'))
jsenv['srcs'].append(jsenv['duktape_src'])

jsenv.Program('#dist/bin/alljoynjs', jsenv['srcs'])
